hushas01/config/routes.rb
Rails.application.routes.draw do
  
  resources :prop_casapi_info2s
  resources :objetivos
  resources :direcciones
  resources :comunas
  resources :regiones
  resources :direcs  
  resources :prop_casapi_infos
  resources :props
     
  #Generamos la Api
  get 'api/new'
  get 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  post 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  get 'api/delete_all' => 'api#deleteAll'
  get 'api/buscarcodigo' => 'api#findCodigoPi' #, :fuente=>:PortalInmobiliario
  get 'api/procesarCasasLC' => 'api#procesarCasasLC' #, :fuente=>:PortalInmobiliario
  
  #fin metodos de la api

  #Generamos los servicios de la Página
  root 'servicios#index'
  get 'servicios/buscador' => 'servicios#buscador'
  get 'servicios/nueva_busqueda' => 'servicios#nueva_busqueda'
  get 'servicios/objetivo' => 'servicios#index3'
  get 'servicios/download' => 'servicios#download'
  get 'servicios/prueba' => 'servicios#prueba'
  
  #fin de los servicios
  
  #otros links

  get 'servicios/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hushas01/app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  
  def index     
  end
  
  def index3
    #@prop_casapi_info2s = PropCasapiInfo2.where("Estado = ?", "objetivo")
    #@prop_casapi_info2s = PropCasapiInfo2.where("Sector = ? and estado=?", "las-condes-metropolitana","Aplica")
    #@prop_casapi_info2s=PropCasapiInfo2.where("Sector = ?", "las-condes-metropolitana").paginate(:page => params[:page], :per_page => 20)
    date = DateTime.now.utc
    date2=date-14.days
    @prop_casapi_info2s=PropCasapiInfo2.where("Sector = ? and estado=? and created_at>?", "las-condes-metropolitana","Aplica",date2).paginate(:page => params[:page], :per_page => 20)
  end
  
 def prueba
   @prop_casapi_info2s = PropCasapiInfo2.where("Sector = ?", "las-condes-metropolitana").first.attributes.values+PropCasapiInfo2.where("Sector = ?", "las-condes-metropolitana").first.prop.attributes.values
   @headers=PropCasapiInfo2.column_names.to_a+Prop.column_names.to_a
 end

  
  def download
    date = DateTime.now.utc
    date2=date-14.day
    @prop_casapi_info2s = PropCasapiInfo2.where("Sector = ? and estado=? and created_at>?", "las-condes-metropolitana","Aplica",date2)
    @headers=PropCasapiInfo2.column_names.to_a+Prop.column_names.to_a

    respond_to do |format| 
      format.xlsx {render xlsx: 'download',filename: "casas_lc.xlsx"}
      #format.xlsx { render filename =>'download.xlsx' }
      #render xlsx: 'download',filename: "casas.xlsx"
    end

  #render xlsx: 'download'#,filename: "casas_lc.xlsx"
  end
  
  def buscador
    @comunas = Comuna.all
  end
  
  def nueva_busqueda
    
    pais='Santiago, Chile'
    
    @direccion = Direccion.new(buscador_params)      
    direccion_completa=@direccion.direccion + ', '+@direccion.comuna.nombre + ', ' + pais
    
    #se busca la direccion
    georeferencia=Geocoder.search(direccion_completa)[0]
    
    #se guarda la lat y longitud
    
    @direccion.longitude=georeferencia.longitude
    @direccion.latitude=georeferencia.latitude
    
    #se va a buscar el plan regulador
    layer = ArcREST::Layer.new(@direccion.comuna.PRC_link)
   
    params = {
      geometryType: "esriGeometryPoint",
      spatialRel: "esriSpatialRelIntersects",
      inSR: 4326,
      units: "esriSRUnit_Meter",
      geometry:{x:@direccion.longitude, 
      y:@direccion.latitude, 
      spatialReference: {wkid: 4326}}
    }
    
    features = layer.features(params)
    
    @direccion.Argis_json=features.to_json
      
    if features.count>0 
      @direccion.zona=features.first['attributes']['ZONA']
    end
   
    if @direccion.save()
      redirect_to @direccion, notice: 'Direccion was successfully created.' 
    else
      render :buscador
    end
  end
  
  def index2
    
=begin
    service_url = "http://geo.minvu.cl/arcgis/rest/services/PRC/13_PRC_Metropolitana/MapServer/48"
    service = Geoservice::MapService.new(url: service_url)
    
    params = {
      geometry: [-33.405573,-70.596150].join(','),
      geometryType: "esriGeometryPoint",
      inSR: 4326,
      spatialRel: "esriSpatialRelIntersects",
      units: "esriSRUnit_Meter",
      returnGeometry: false,
      outFields:"*",
      spatialRel:"esriSpatialRelIntersects",
      returnIdsOnly:false,
      returnCountOnly:false,
      returnZ:false,
      returnM:false,
      returnDistinctValues:false
    }
    features = service.query(0,params)#["features"]
=end
    service_url = "http://geo.minvu.cl/arcgis/rest/services/PRC"
    catalog = ArcREST::Catalog.new(service_url)
    
    service = ArcREST::Service.new('http://geo.minvu.cl/arcgis/rest/services/PRC/13_PRC_Metropolitana/MapServer')
    
    layer = ArcREST::Layer.new('http://geo.minvu.cl/arcgis/rest/services/PRC/13_PRC_Metropolitana/MapServer/48')
=begin    
   
    #-33.405904, -70.596488

=end  
  var=Geocoder.search("lAS NIEVES 3435, vitacura, santiago, Chile")[0]
    
    params = {
      geometryType: "esriGeometryPoint",
      spatialRel: "esriSpatialRelIntersects",
      inSR: 4326,
      units: "esriSRUnit_Meter",
      geometry:{x:var.longitude, 
      y:var.latitude, 
      spatialReference: {wkid: 4326}}
    }
    
    features = layer.features(params)
    #result=layer.query(params).inspect
    
    
    @var1=""#result
    
    @var2= features.first['attributes']['ZONA']
    #@var2=features.first["ZONA"]
  end  
  
  
    # Never trust parameters from the scary internet, only allow the white list through.
  def buscador_params
    params.permit(:direccion, :comuna_id)
  end

end

hushas01/app/helpers/servicios_helper.rb
module ServiciosHelper
end

hushas01/app/views/servicios/buscador.html.erb
<div class="container">
	<h1>Buscador de Plano Regulador</h1>
	<div class="form-group">
		<%= form_tag("/servicios/nueva_busqueda", method: "get") do %>
		<%= label_tag(:direccion, "Dirección:",class: 'form-control') %>
		<%= text_field_tag(:direccion,"", class: 'form-control') %>

<%
=begin
%>
<%= collection_select(:comuna, :comuna_id, @comunas, :id, :nombre) %>
<%
=end
%>
		<%= label_tag(:comuna_id, "Comuna:",class: 'form-control') %>
		<%= select_tag :comuna_id,options_from_collection_for_select(@comunas, :id, :nombre),class: 'form-control'%>

		<%= submit_tag("Buscar") %>
		<% end %>
	</div>
</div>

hushas01/app/views/servicios/index.html.erb
<div class="container">

  <div class="starter-template">
	
	<h1>Servicios#index</h1>
	Hushas!
	<hr />
	
	<h2>Mapa del Sitio</h2>
	
	<br />
	
	<ul>
		<li> API: para interactuar con la BD con JSON</li>
		<li> <%=link_to "Comunas",comunas_path%>: Todas las comunas con el link del PRC</li>
		<li> <%=link_to "Regiones",regiones_path%>: Todas las regiones</li>
		<li> <%=link_to "Direcciones",direcciones_path%>: Todas las direcciones quedan registradas del buscador</li>
		<li> <%=link_to "Direcs",direcs_path%>: OBSOLETO</li>
		<li> <%=link_to "Servicios",servicios_index_path%>: Todos los servicios para el usuario</li>
		<li> <%=link_to "props",props_path%>: Propiedades PI</li>
		<li> <%=link_to "prop_casapi_infos",prop_casapi_infos_path%>: OBSOLETO</li>
		<li> <%=link_to "prop_casapi_infos2",prop_casapi_info2s_path%>: Detalle propiedades casas PI2</li>
		<li> <%=link_to "Objetivos",objetivos_path%>: Detalle propiedades casas PI</li>
		
	</ul>
	
	<br />
	<hr />
	API
	<ul>
		<li> delete_all</li>
		<li> new_pi</li>
		<li> buscarcodigo</li>
		<li> procesarCasasLC</li>		
	</ul>	
		
	<hr />
	
	<ul>
		<li> Agregar datos de casas faltantes. lat, lng, zona, valor uf, precio uf, zona, objetivo, estados, nombre, telefono, correo vendedor</li>
		<li> Modificar el servicio para crear propiedad</li>
		<li> Modificar crawler y cargar información</li>
		<li> Crear servicio para procesar casas</li>
		<li> Generar Reporte de casas que cumplan</li>
		<li> Generar Correo automatico</li>
		<li> _________________</li>
		<li> Index básico</li>
		<li> Generar la BD</li>
		<li> Generar servicio para cargar información</li>
		<li> Generar página de busqueda de propiedades</li>
		<li> python. cargar la infomación</li>
		<li> Servicio para validar si una propiedad está cargada</li>
		<li> api georeferencia y plan regulador</li>
		<li> generar alertas de correo</li>
		<li> Mejorar página inicial</li>
		<li> extraer info de tt</li>
		<li> extraer info de em</li>   
	</ul>   
	 <script>
var bootstrap3_enabled = (typeof $().emulateTransitionEnd == 'function');
</script>
	 
	 <button type="button" onclick="document.getElementById('demo').innerHTML = bootstrap3_enabled">
	 	Click me to display BS</button>

	<p id="demo"></p>
	 
  </div>
</div>

hushas01/app/views/servicios/index3.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Prop Casapi Info2s</h1>

<div>
<%= will_paginate @prop_casapi_info2s %>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Prop</th>
      <th>Creado</th>
      <th>Publicacion</th>
      <th>Precio</th>
      <th>Sector</th>
      <th>Direccion</th>
      <th>Programa</th>
      <th>Superficie</th>
      <th>Descripcion</th>
      <th>Sup construida</th>
      <th>Sup terreno</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Zona</th>
      <th>Precio uf</th>
      <th>Precio uf-m2</th>
      <th>Objetivo uf-m2</th>
      <th>Estado</th>
      <th>Contacto</th>
      <th>Telefono</th>
      <th>Correo</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prop_casapi_info2s.each do |prop_casapi_info2| %>
      <tr>
      	<td><%= link_to 'Ver Detalle Propiedad',prop_casapi_info2.prop %></td>
      	<td><%= prop_casapi_info2.created_at %></td>
        <td><%= prop_casapi_info2.publicacion %></td>
        <td><%= prop_casapi_info2.precio %></td>
        <td><%= prop_casapi_info2.sector %></td>
        <td><%= prop_casapi_info2.direccion %></td>
        <td><%= prop_casapi_info2.programa %></td>
        <td><%= prop_casapi_info2.superficie %></td>
        <td><%= prop_casapi_info2.descripcion %></td>
        <td><%= prop_casapi_info2.sup_construida %></td>
        <td><%= prop_casapi_info2.sup_terreno %></td>
        <td><%= prop_casapi_info2.lat %></td>
        <td><%= prop_casapi_info2.lng %></td>
        <td><%= prop_casapi_info2.zona %></td>
        <td><%= prop_casapi_info2.valor_uf %></td>
        <td><%= prop_casapi_info2.precio_uf %></td>
        <td><%= prop_casapi_info2.objetivo %></td>
        <td><%= prop_casapi_info2.estado %></td>
        <td><%= prop_casapi_info2.contacto %></td>
        <td><%= prop_casapi_info2.telefono %></td>
        <td><%= prop_casapi_info2.correo %></td>        
        <td><%= link_to 'Show', prop_casapi_info2 %></td>
        <td><%= link_to 'Edit', edit_prop_casapi_info2_path(prop_casapi_info2) %></td>
        <td><%= link_to 'Destroy', prop_casapi_info2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Prop Casapi Info2', new_prop_casapi_info2_path %>
</div>

hushas01/app/views/servicios/nueva_busqueda.html.erb
<div class="container">
<h1>Resultado</h1>

<%=@var %>
	
</div>

hushas01/app/views/servicios/prueba.html.erb
<%=@headers%>
<br />
<%=@prop_casapi_info2s%>