hushas01/config/routes.rb
Rails.application.routes.draw do
  
  resources :prop_casapi_info2s
  resources :objetivos
  resources :direcciones
  resources :comunas
  resources :regiones
  resources :direcs  
  resources :prop_casapi_infos
  resources :props
     
  #Generamos la Api
  get 'api/new'
  get 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  post 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  get 'api/delete_all' => 'api#deleteAll'
  get 'api/buscarcodigo' => 'api#findCodigoPi' #, :fuente=>:PortalInmobiliario
  get 'api/procesarCasasLC' => 'api#procesarCasasLC' #, :fuente=>:PortalInmobiliario
  
  #fin metodos de la api

  #Generamos los servicios de la Página
  root 'servicios#index'
  get 'servicios/buscador' => 'servicios#buscador'
  get 'servicios/nueva_busqueda' => 'servicios#nueva_busqueda'
  get 'servicios/objetivo' => 'servicios#index3'
  get 'servicios/download' => 'servicios#download'
  get 'servicios/prueba' => 'servicios#prueba'
  
  #fin de los servicios
  
  #otros links

  get 'servicios/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hushas01/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hushas01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <nav class="navbar navbar navbar-fixed-top navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

          </button>
          <div class="navbar-brand">Hushas</div>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%=link_to "Home",root_path%> </li>
            <li><%=link_to "Buscador PRC",servicios_buscador_path%></li>
            <li><%=link_to "Props",props_path%></li>
            <li><%=link_to "Casas PI",prop_casapi_info2s_path%></li>
            <li><%=link_to "Casas PI objetivo",servicios_objetivo_path%></li>
            <li><%=link_to "Correr Proceso",api_procesarCasasLC_path%></li>
            <li><%=link_to "Descargar Casas",servicios_download_path(format: :xlsx)%></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <%= yield %>  
      
	<footer class="footer">
      <div class="container footerdiv">
        <span>HusHas</span>
      </div>
    </footer>
    


  </body>



</html>