hushas01/config/routes.rb
Rails.application.routes.draw do
  
  resources :prop_casapi_info2s
  resources :objetivos
  resources :direcciones
  resources :comunas
  resources :regiones
  resources :direcs  
  resources :prop_casapi_infos
  resources :props
     
  #Generamos la Api
  get 'api/new'
  get 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  post 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  get 'api/delete_all' => 'api#deleteAll'
  get 'api/buscarcodigo' => 'api#findCodigoPi' #, :fuente=>:PortalInmobiliario
  get 'api/procesarCasasLC' => 'api#procesarCasasLC' #, :fuente=>:PortalInmobiliario
  
  #fin metodos de la api

  #Generamos los servicios de la Página
  root 'servicios#index'
  get 'servicios/buscador' => 'servicios#buscador'
  get 'servicios/nueva_busqueda' => 'servicios#nueva_busqueda'
  get 'servicios/objetivo' => 'servicios#index3'
  get 'servicios/download' => 'servicios#download'
  get 'servicios/prueba' => 'servicios#prueba'
  
  #fin de los servicios
  
  #otros links

  get 'servicios/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hushas01/app/models/prop.rb
class Prop < ApplicationRecord
end

hushas01/app/controllers/props_controller.rb
class PropsController < ApplicationController
  before_action :set_prop, only: [:show, :edit, :update, :destroy]

  # GET /props
  # GET /props.json
  def index
    @props = Prop.all
  end

  # GET /props/1
  # GET /props/1.json
  def show
  end

  # GET /props/new
  def new
    @prop = Prop.new
  end

  # GET /props/1/edit
  def edit
  end

  # POST /props
  # POST /props.json
  def create
    @prop = Prop.new(prop_params)

    respond_to do |format|
      if @prop.save
        format.html { redirect_to @prop, notice: 'Prop was successfully created.' }
        format.json { render :show, status: :created, location: @prop }
      else
        format.html { render :new }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /props/1
  # PATCH/PUT /props/1.json
  def update
    respond_to do |format|
      if @prop.update(prop_params)
        format.html { redirect_to @prop, notice: 'Prop was successfully updated.' }
        format.json { render :show, status: :ok, location: @prop }
      else
        format.html { render :edit }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /props/1
  # DELETE /props/1.json
  def destroy
    @prop.destroy
    respond_to do |format|
      format.html { redirect_to props_url, notice: 'Prop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prop
      @prop = Prop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prop_params
      params.require(:prop).permit(:fuente, :url, :codigo, :operacion, :tipo)
    end
end

hushas01/app/helpers/props_helper.rb
module PropsHelper
end

hushas01/app/views/props/_form.html.erb
<%= form_for(prop) do |f| %>
  <% if prop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prop.errors.count, "error") %> prohibited this prop from being saved:</h2>

      <ul>
      <% prop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fuente %>
    <%= f.text_field :fuente %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :codigo %>
    <%= f.number_field :codigo %>
  </div>

  <div class="field">
    <%= f.label :operacion %>
    <%= f.text_field :operacion %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hushas01/app/views/props/edit.html.erb
<div class="container">
	<h1>Editing Prop</h1>

<%= render 'form', prop: @prop %>

<%= link_to 'Show', @prop %> |
<%= link_to 'Back', props_path %>
</div>

hushas01/app/views/props/index.html.erb
<div class="container">
	<p id="notice">
		<%= notice %>
	</p>

	<h1>Props</h1>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>Fuente</th>
					<th>Url</th>
					<th>Codigo</th>
					<th>Operacion</th>
					<th>Tipo</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @props.each do |prop| %>
				<tr>
					<td><%= prop.fuente %></td>
					<td><%= link_to 'Link',prop.url %></td>
					<td><%= prop.codigo %></td>
					<td><%= prop.operacion %></td>
					<td><%= prop.tipo %></td>
					<td><%= link_to 'Show', prop %></td>
					<td><%= link_to 'Edit', edit_prop_path(prop) %></td>
					<td><%= link_to 'Destroy', prop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
				<% end %>

		</table>
	</div>
</div>
<div class="container">
	<%= link_to 'New Prop', new_prop_path %>

</div>

hushas01/app/views/props/new.html.erb
<h1>New Prop</h1>

<%= render 'form', prop: @prop %>

<%= link_to 'Back', props_path %>

hushas01/app/views/props/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Fuente:</strong>
  <%= @prop.fuente %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @prop.url,@prop.url %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @prop.codigo %>
</p>

<p>
  <strong>Operacion:</strong>
  <%= @prop.operacion %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @prop.tipo %>
</p>

<%= link_to 'Edit', edit_prop_path(@prop) %> |
<%= link_to 'Back', props_path %>

</div>