hushas01/config/routes.rb
Rails.application.routes.draw do
  
  resources :prop_casapi_info2s
  resources :objetivos
  resources :direcciones
  resources :comunas
  resources :regiones
  resources :direcs  
  resources :prop_casapi_infos
  resources :props
     
  #Generamos la Api
  get 'api/new'
  get 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  post 'api/new_pi' => 'api#new', :fuente=>:PortalInmobiliario
  get 'api/delete_all' => 'api#deleteAll'
  get 'api/buscarcodigo' => 'api#findCodigoPi' #, :fuente=>:PortalInmobiliario
  get 'api/procesarCasasLC' => 'api#procesarCasasLC' #, :fuente=>:PortalInmobiliario
  
  #fin metodos de la api

  #Generamos los servicios de la Página
  root 'servicios#index'
  get 'servicios/buscador' => 'servicios#buscador'
  get 'servicios/nueva_busqueda' => 'servicios#nueva_busqueda'
  get 'servicios/objetivo' => 'servicios#index3'
  get 'servicios/download' => 'servicios#download'
  get 'servicios/prueba' => 'servicios#prueba'
  
  #fin de los servicios
  
  #otros links

  get 'servicios/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hushas01/app/models/direc.rb
class Direc < ApplicationRecord
end

hushas01/app/controllers/direcs_controller.rb
class DirecsController < ApplicationController
  before_action :set_direc, only: [:show, :edit, :update, :destroy]

  # GET /direcs
  # GET /direcs.json
  def index
    @direcs = Direc.all
  end

  # GET /direcs/1
  # GET /direcs/1.json
  def show
  end

  # GET /direcs/new
  def new
    @direc = Direc.new
  end

  # GET /direcs/1/edit
  def edit
  end

  # POST /direcs
  # POST /direcs.json
  def create
    @direc = Direc.new(direc_params)

    respond_to do |format|
      if @direc.save
        
        var=Geocoder.search(@direc.direccion)[0]
        layer = ArcREST::Layer.new('http://geo.minvu.cl/arcgis/rest/services/PRC/13_PRC_Metropolitana/MapServer/48')
        params = {
          geometryType: "esriGeometryPoint",
          spatialRel: "esriSpatialRelIntersects",
          inSR: 4326,
          units: "esriSRUnit_Meter",
          geometry:{x:var.longitude, 
          y:var.latitude, 
          spatialReference: {wkid: 4326}}
        }

        features = layer.features(params)
        
        @direc.longitude=var.longitude
        @direc.latitude=var.latitude
        @direc.Argis_json=features
        if features.count>0 
          @direc.zona=features.first['attributes']['ZONA']
        end        
        @direc.save

        format.html { redirect_to @direc, notice: 'Direc was successfully created.' }
        format.json { render :show, status: :created, location: @direc }
      else
        format.html { render :new }
        format.json { render json: @direc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direcs/1
  # PATCH/PUT /direcs/1.json
  def update
    respond_to do |format|
      if @direc.update(direc_params)
        format.html { redirect_to @direc, notice: 'Direc was successfully updated.' }
        format.json { render :show, status: :ok, location: @direc }
      else
        format.html { render :edit }
        format.json { render json: @direc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direcs/1
  # DELETE /direcs/1.json
  def destroy
    @direc.destroy
    respond_to do |format|
      format.html { redirect_to direcs_url, notice: 'Direc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direc
      @direc = Direc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direc_params
      params.require(:direc).permit(:direccion, :latitude, :longitude, :Argis_json, :zona)
    end
end

hushas01/app/helpers/direcs_helper.rb
module DirecsHelper
end

hushas01/app/views/direcs/_form.html.erb
<%= form_for(direc) do |f| %>
  <% if direc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(direc.errors.count, "error") %> prohibited this direc from being saved:</h2>

      <ul>
      <% direc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :Argis_json %>
    <%= f.text_field :Argis_json %>
  </div>

  <div class="field">
    <%= f.label :zona %>
    <%= f.text_field :zona %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hushas01/app/views/direcs/edit.html.erb
<h1>Editing Direc</h1>

<%= render 'form', direc: @direc %>

<%= link_to 'Show', @direc %> |
<%= link_to 'Back', direcs_path %>

hushas01/app/views/direcs/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Direcs</h1>

	<div class="table-responsive">
		<table class="table">
  <thead>
    <tr>
      <th>Direccion</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Argis json</th>
      <th>Zona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @direcs.each do |direc| %>
      <tr>
        <td><%= direc.direccion %></td>
        <td><%= direc.latitude %></td>
        <td><%= direc.longitude %></td>
        <td><%= direc.Argis_json %></td>
        <td><%= direc.zona %></td>
        <td><%= link_to 'Show', direc %></td>
        <td><%= link_to 'Edit', edit_direc_path(direc) %></td>
        <td><%= link_to 'Destroy', direc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Direc', new_direc_path %>
</div>

hushas01/app/views/direcs/new.html.erb
<div class="container">
<h1>New Direc </h1>
<h2>Importante -->Por ahora SOLO con Vitacura</h2>
<h2>Importante -->Agregar dirección completa, con comuna y ciudad</h2>

<%= render 'form', direc: @direc %>

<%= link_to 'Back', direcs_path %>
</div>

hushas01/app/views/direcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Direccion:</strong>
  <%= @direc.direccion %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @direc.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @direc.longitude %>
</p>

<p>
  <strong>Argis json:</strong>
  <%= @direc.Argis_json %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @direc.zona %>
</p>

<%= link_to 'Edit', edit_direc_path(@direc) %> |
<%= link_to 'Back', direcs_path %>